application: therapidteam 
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /css
  static_dir: css 
- url: /js
  static_dir: js 
- url: /img
  static_dir: img 
- url: /less
  static_dir: less 
- url: /fonts
  static_dir: fonts 



- url: /testreq
  script: testrequests.application
  login: required
  
- url: /.*
  script: testrequests.application
  login: required
